#!/bin/bash
# ============================================
# Combine Agent Schemas
# 
# This script reads all agent SQL files and combines
# them into a single init script for Postgres.
#
# Usage: ./combine-schemas.sh [phase]
#   phase: 1, 2, or 3 (optional, defaults to all)
# ============================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_DIR="$SCRIPT_DIR/../agents"
OUTPUT_FILE="$SCRIPT_DIR/../init/01-combined-agents.sql"

# Optional phase filter
PHASE_FILTER="${1:-all}"

echo "Combining agent schemas..."
echo "Phase filter: $PHASE_FILTER"
echo "Output: $OUTPUT_FILE"

# Start with header
cat > "$OUTPUT_FILE" << 'EOF'
-- ============================================
-- COMBINED AGENT SCHEMAS
-- Auto-generated by combine-schemas.sh
-- DO NOT EDIT DIRECTLY - edit individual agent files
-- ============================================

-- This file is generated from individual agent schema files.
-- Each section below is sourced from a separate file in the agents/ directory.

EOF

# Add generation timestamp
echo "-- Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Function to check if file matches phase filter
should_include() {
    local file="$1"
    if [ "$PHASE_FILTER" = "all" ]; then
        return 0
    fi
    
    # Extract phase from file
    local phase=$(grep -m1 "Phase:" "$file" | grep -oE "[0-9]+" || echo "0")
    
    if [ "$phase" -le "$PHASE_FILTER" ]; then
        return 0
    fi
    return 1
}

# Process each agent file (excluding template)
for agent_file in "$AGENTS_DIR"/*.sql; do
    filename=$(basename "$agent_file")
    
    # Skip template
    if [ "$filename" = "_template.sql" ]; then
        continue
    fi
    
    # Check phase filter
    if ! should_include "$agent_file"; then
        echo "Skipping $filename (phase > $PHASE_FILTER)"
        continue
    fi
    
    echo "Including $filename..."
    
    # Add separator and source reference
    echo "" >> "$OUTPUT_FILE"
    echo "-- ============================================" >> "$OUTPUT_FILE"
    echo "-- Source: agents/$filename" >> "$OUTPUT_FILE"
    echo "-- ============================================" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    # Append file content
    cat "$agent_file" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

echo ""
echo "Schema combination complete!"
echo "Tables will be created when Postgres container starts."

# Show summary
echo ""
echo "Summary of included agents:"
grep -h "^-- Agent:" "$OUTPUT_FILE" | sed 's/-- /  /'

